# Generated by Django 4.1 on 2022-08-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarsAds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_to_ad", models.URLField(unique=True, verbose_name="link_to_ad")),
                ("title_ad", models.TextField(max_length=500, verbose_name="title_ad")),
                (
                    "seller_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="seller_name"
                    ),
                ),
                (
                    "car_price",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="car_price"
                    ),
                ),
                (
                    "link_to_car_img",
                    models.URLField(blank=True, verbose_name="link_to_car_img"),
                ),
            ],
            options={
                "verbose_name": "Объявление о продаже автомобиля",
                "verbose_name_plural": "Объявления о продажах автомобилей",
            },
        ),
    ]
