# Generated by Django 4.1 on 2022-08-25 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("olxparser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carsads",
            name="ad_created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="ad_created",
            ),
            preserve_default=False,
        ),
    ]
